# makefile for GNU make (automatically generated by makemake 28-Mar-13, 22:27:41)
# NOTE: indent with TAB in GNU makefiles!

# MESSAGES #

COMPILE_FILE=printf "\033[K\033[0;33mCompiling \033[1;33m$<\033[0;33m...\033[0m\n"
TARGET_DONE=printf "\033[K\033[0;32mTarget \"$@\" successfully done.\033[0m\n"
MERGING=printf "\033[K\033[1;34mLibrary merging \"$@\"... \033[0m\n"

# VERSION DEFINES #

VERSION = -D__AMIGADATE__=\"\ \($(shell date "+%d.%m.%Y")\)\ \" -D__COPYRIGHT__=\"©\ $(shell date "+%Y")\ Filip\ \'\widelec\'\ Maryjañski\"

# PROJECT #
# paths are relative to the project directory (current directory during make)

OUTFILE = libiksemel.a

OUTDIR  = ./
OBJDIR  = ./

PROJECT = $(OUTDIR)$(OUTFILE)

# COMPILER #
CC = ppc-morphos-gcc-11
CWARNS = -Wall
CDEFS  = $(VERSION) -D__NOLIBBASE__ -DUSE_INLINE_STDARG -D__MORPHOS_NOSTDLIB__ -DHAVE_OPENSSL
# -D__DEBUG__
CFLAGS = -O3 -noixemul -fno-builtin
CLIBS  =

COMPILE = $(CC) $(TARGET) $(CWARNS) $(CDEFS) $(CFLAGS) $(CLIBS)

# AR #
AR = ppc-morphos-gcc-ar-11
ARPARMS = rs

# target 'all' (default target)
all: $(PROJECT)
	@$(TARGET_DONE)

# target 'compiler' (compile target)
$(OBJDIR)base64.c.o: base64.c common.h iksemel.h
	@$(COMPILE_FILE)
	@$(COMPILE) -c -o $(OBJDIR)base64.c.o base64.c

$(OBJDIR)dom.c.o: dom.c common.h iksemel.h
	@$(COMPILE_FILE)
	@$(COMPILE) -c -o $(OBJDIR)dom.c.o dom.c

$(OBJDIR)filter.c.o: filter.c common.h iksemel.h
	@$(COMPILE_FILE)
	@$(COMPILE) -c -o $(OBJDIR)filter.c.o filter.c

$(OBJDIR)iks.c.o: iks.c common.h iksemel.h
	@$(COMPILE_FILE)
	@$(COMPILE) -c -o $(OBJDIR)iks.c.o iks.c

$(OBJDIR)ikstack.c.o: ikstack.c common.h iksemel.h
	@$(COMPILE_FILE)
	@$(COMPILE) -c -o $(OBJDIR)ikstack.c.o ikstack.c

$(OBJDIR)morphos_io.c.o: morphos_io.c common.h iksemel.h
	@$(COMPILE_FILE)
	@$(COMPILE) -c -o $(OBJDIR)morphos_io.c.o morphos_io.c

$(OBJDIR)jabber.c.o: jabber.c common.h iksemel.h
	@$(COMPILE_FILE)
	@$(COMPILE) -c -o $(OBJDIR)jabber.c.o jabber.c

$(OBJDIR)md5.c.o: md5.c common.h iksemel.h
	@$(COMPILE_FILE)
	@$(COMPILE) -c -o $(OBJDIR)md5.c.o md5.c

$(OBJDIR)sax.c.o: sax.c common.h iksemel.h
	@$(COMPILE_FILE)
	@$(COMPILE) -c -o $(OBJDIR)sax.c.o sax.c

$(OBJDIR)sha.c.o: sha.c common.h iksemel.h
	@$(COMPILE_FILE)
	@$(COMPILE) -c -o $(OBJDIR)sha.c.o sha.c

$(OBJDIR)stream.c.o: stream.c common.h iksemel.h
	@$(COMPILE_FILE)
	@$(COMPILE) -c -o $(OBJDIR)stream.c.o stream.c

$(OBJDIR)utility.c.o: utility.c common.h iksemel.h
	@$(COMPILE_FILE)
	@$(COMPILE) -c -o $(OBJDIR)utility.c.o utility.c

$(OBJDIR)morphos.c.o: morphos.c
	@$(COMPILE_FILE)
	@$(COMPILE) -c -o $(OBJDIR)morphos.c.o morphos.c

$(OBJDIR)tls-openssl.c.o: tls-openssl.c common.h iksemel.h
	@$(COMPILE_FILE)
	@$(COMPILE) -c -o $(OBJDIR)tls-openssl.c.o tls-openssl.c

$(OBJDIR)http.c.o: http.c common.h finetune.h iksemel.h http.h
	@$(COMPILE_FILE)
	@$(COMPILE) -c -o $(OBJDIR)http.c.o http.c

$(OBJDIR)urlencode.c.o: urlencode.c common.h finetune.h urlencode.h
	@$(COMPILE_FILE)
	@$(COMPILE) -c -o $(OBJDIR)urlencode.c.o urlencode.c

OBJS = $(OBJDIR)base64.c.o $(OBJDIR)dom.c.o $(OBJDIR)filter.c.o $(OBJDIR)iks.c.o\
 $(OBJDIR)ikstack.c.o $(OBJDIR)morphos_io.c.o $(OBJDIR)jabber.c.o $(OBJDIR)md5.c.o $(OBJDIR)sax.c.o\
 $(OBJDIR)sha.c.o $(OBJDIR)stream.c.o $(OBJDIR)utility.c.o $(OBJDIR)morphos.c.o $(OBJDIR)tls-openssl.c.o\
 $(OBJDIR)http.c.o $(OBJDIR)urlencode.c.o

# link all file(s)
$(PROJECT): $(OBJS)
	@$(MERGING)
	@$(AR) $(ARPARMS) $@ $(OBJS)

# any other targets

clean:
	@-rm -rf $(PROJECT)
	@-rm -rf $(OBJDIR)*.o
	@$(TARGET_DONE)

